spring.application.name=PruebaTecnicaJesus
# ===============================
# CONEXION A H2 (EN MEMORIA)
# ===============================
spring.datasource.url=jdbc:h2:mem:polizasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# ===============================
# CONFIGURACION DE JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONSOLA WEB DE H2 (Para que puedas ver tus datos)
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true